### ISSUE TITLE
The vray5.13 rendering elements in max2022 cannot be saved

### ISSUE THREAD

**Issue by Qiuyuwuhen** [usakhelo/batchcam#6]
The vray5.13 rendering elements in max2022 cannot be saved

**Comment by usakhelo** [comment]
Thanks for reporting. I will need to get access to vray5 somehow to make it work.
Are there any error messages?

**Comment by FeanorFS** [comment]
I can confirm similar problem - Vray 5 + 3dsMax 2020. When a sequence is rendering, Lens Effects applies to the 1st image only, then the layer disables ("eye" disappears) and other images are saving without effect.  If I select "Save Glare channel" - it saves, but separately. I attached screenshot.
*anyway - thank you for you work, it helps a lot!
![Clipboard01](https://user-images.githubusercontent.com/108021966/183744846-eb5bf7a2-cd52-4c1d-95b8-1e7a0ca8ca61.jpg)

**Comment by usakhelo** [comment]
@FeanorFS , is this the Vray camera properties on your screenshot? Or it's Vray frame buffer?

**Comment by FeanorFS** [comment]
It's Vray frame buffer.

> Message ID: ***@***.***>
>
*this issue fixed somehow by itself in of my files, I will investigate the
differences when it finishes task in 2 days.

**Comment by FeanorFS** [comment]
Hi again, I found the cause of that situation, it seems like Vray's problem.
The "Autoswitch.." checkbox must be on to have Denoiser+Lens Effects saved.
[image: image.png]

Thanks,
have a good day!
